#include <cassert> 

int main()
{
  assert(0);
}

// I AM ASSUMING WERE ABORTING BECAUSE THESE ARE TESTS
// BASED ON GIT PRE-PUSH IF YOU EXIT 1 FROM THE PYTHON SCRIPT, IT WILL NOT PUSH, RIGHT?
